In [9]:
import pandas as pd
import torch
from gensim.models import KeyedVectors
import warnings

warnings.filterwarnings('ignore')

In [6]:
gpt_data = pd.read_csv(r'D:\ML_Projects\AI_Tech_ChatBot\Data\ChatGPT_chatlogs\GPT_chatlogs_all.csv')
word2vec_model = KeyedVectors.load_word2vec_format(r'D:\ML_Projects\Vehicle_Insurance_Claims_Prediction\models\GoogleNews-vectors-negative300.bin', binary=True)

In [4]:
gpt_data['Question'][0].split()

['What', 'is', 'contrastive', 'loss']

In [7]:
def get_word_vector(words):
    try:
        return torch.tensor([word2vec_model[word] for word in words], dtype=torch.float)
    except KeyError:
        return torch.zeros(word2vec_model.vector_size, dtype=torch.float)

In [ ]:
vec = []
print_lim = 0
for i in range(len(gpt_data)):
    if print_lim == 1:
        break
    words = gpt_data['Question'][i].split()
    vec.append(get_word_vector(words))
    #list(map(lambda w: get_word_vector(w), words))
    print_lim+=1

    print("actual word: ", gpt_data['Question'][i].split()[1],
        "Predicted word: ", word2vec_model.similar_by_vector(get_word_vector(gpt_data['Question'][i].split()), topn=1)[0])

In [11]:
for i in range(4):
    print(get_word_vector(gpt_data['Question'][i].split()))

tensor([[-0.0231,  0.1533,  0.1523,  ...,  0.1445,  0.1328, -0.0859],
        [ 0.0070, -0.0732,  0.1719,  ...,  0.0112,  0.1641,  0.1069],
        [-0.0072, -0.0791,  0.1069,  ..., -0.0269, -0.0322,  0.2070],
        [ 0.0747,  0.1553, -0.0007,  ..., -0.0547, -0.0461, -0.1118]])
tensor([[ 0.1533,  0.1230,  0.1650,  ..., -0.2871, -0.3125,  0.1318],
        [-0.0179,  0.1172,  0.0527,  ..., -0.0332,  0.1494, -0.1191],
        [ 0.0073,  0.1006, -0.0601,  ..., -0.0669,  0.0400, -0.0610],
        ...,
        [-0.0118, -0.0474,  0.0447,  ...,  0.0713, -0.0349,  0.0242],
        [-0.0072, -0.0791,  0.1069,  ..., -0.0269, -0.0322,  0.2070],
        [-0.0884,  0.1484, -0.0630,  ...,  0.0203,  0.1162,  0.1758]])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0

In [ ]:
word2vec_model.similar_by_vector(get_word_vector(gpt_data['Question'][i].split()), topn=1)

In [13]:
import numpy as np
import pandas as pd
from gensim.models import KeyedVectors

In [14]:
word2vec_model = KeyedVectors.load_word2vec_format(r'D:\ML_Projects\Vehicle_Insurance_Claims_Prediction\models\GoogleNews-vectors-negative300.bin', binary=True)

def get_word_vector(word):
    try:
        return word2vec_model[word]
    except KeyError:
        return np.zeros(300)

gpt_data = pd.read_csv(r'D:\ML_Projects\AI_Tech_ChatBot\Data\ChatGPT_chatlogs\GPT_chatlogs_all.csv')

vec = []
for i in range(len(gpt_data)):
    words = gpt_data['Question'][i].split()
    vec.append([get_word_vector(w) for w in words])

In [32]:
print(gpt_data['Question'][100000])
print(len(vec[100000]))
print(len(vec[100000][12]))

Ok. But what about human resourse department, finance department and other managerial department
13
300


In [24]:
len(gpt_data)

383234

In [40]:
import pandas as pd
gpt_data = pd.read_csv(r'D:\ML_Projects\AI_Tech_ChatBot\Data\ChatGPT_chatlogs\GPT_chatlogs_all.csv')

for i in range(len(gpt_data)):
    print(gpt_data['Question'][i])
    break

What is contrastive loss
