In [9]:
import pandas as pd
import torch
from gensim.models import KeyedVectors
import warnings

warnings.filterwarnings('ignore')

In [6]:
gpt_data = pd.read_csv(r'D:\ML_Projects\AI_Tech_ChatBot\Data\ChatGPT_chatlogs\GPT_chatlogs_all.csv')
word2vec_model = KeyedVectors.load_word2vec_format(r'D:\ML_Projects\Vehicle_Insurance_Claims_Prediction\models\GoogleNews-vectors-negative300.bin', binary=True)

In [4]:
gpt_data['Question'][0].split()

['What', 'is', 'contrastive', 'loss']

In [7]:
def get_word_vector(words):
    try:
        return torch.tensor([word2vec_model[word] for word in words], dtype=torch.float)
    except KeyError:
        return torch.zeros(word2vec_model.vector_size, dtype=torch.float)

In [ ]:
vec = []
print_lim = 0
for i in range(len(gpt_data)):
    if print_lim == 1:
        break
    words = gpt_data['Question'][i].split()
    vec.append(get_word_vector(words))
    #list(map(lambda w: get_word_vector(w), words))
    print_lim+=1

    print("actual word: ", gpt_data['Question'][i].split()[1],
        "Predicted word: ", word2vec_model.similar_by_vector(get_word_vector(gpt_data['Question'][i].split()), topn=1)[0])

In [11]:
for i in range(4):
    print(get_word_vector(gpt_data['Question'][i].split()))

tensor([[-0.0231,  0.1533,  0.1523,  ...,  0.1445,  0.1328, -0.0859],
        [ 0.0070, -0.0732,  0.1719,  ...,  0.0112,  0.1641,  0.1069],
        [-0.0072, -0.0791,  0.1069,  ..., -0.0269, -0.0322,  0.2070],
        [ 0.0747,  0.1553, -0.0007,  ..., -0.0547, -0.0461, -0.1118]])
tensor([[ 0.1533,  0.1230,  0.1650,  ..., -0.2871, -0.3125,  0.1318],
        [-0.0179,  0.1172,  0.0527,  ..., -0.0332,  0.1494, -0.1191],
        [ 0.0073,  0.1006, -0.0601,  ..., -0.0669,  0.0400, -0.0610],
        ...,
        [-0.0118, -0.0474,  0.0447,  ...,  0.0713, -0.0349,  0.0242],
        [-0.0072, -0.0791,  0.1069,  ..., -0.0269, -0.0322,  0.2070],
        [-0.0884,  0.1484, -0.0630,  ...,  0.0203,  0.1162,  0.1758]])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0

In [ ]:
word2vec_model.similar_by_vector(get_word_vector(gpt_data['Question'][i].split()), topn=1)

In [13]:
import numpy as np
import pandas as pd
from gensim.models import KeyedVectors

In [14]:
word2vec_model = KeyedVectors.load_word2vec_format(r'D:\ML_Projects\Vehicle_Insurance_Claims_Prediction\models\GoogleNews-vectors-negative300.bin', binary=True)

def get_word_vector(word):
    try:
        return word2vec_model[word]
    except KeyError:
        return np.zeros(300)

gpt_data = pd.read_csv(r'D:\ML_Projects\AI_Tech_ChatBot\Data\ChatGPT_chatlogs\GPT_chatlogs_all.csv')

vec = []
for i in range(len(gpt_data)):
    words = gpt_data['Question'][i].split()
    vec.append([get_word_vector(w) for w in words])

In [32]:
print(gpt_data['Question'][100000])
print(len(vec[100000]))
print(len(vec[100000][12]))

Ok. But what about human resourse department, finance department and other managerial department
13
300


In [24]:
len(gpt_data)

383234

In [40]:
import pandas as pd
gpt_data = pd.read_csv(r'D:\ML_Projects\AI_Tech_ChatBot\Data\ChatGPT_chatlogs\GPT_chatlogs_all.csv')

for i in range(len(gpt_data)):
    print(gpt_data['Question'][i])
    break

What is contrastive loss


In [1]:
from gensim.models import KeyedVectors
import numpy as np
import pandas as pd

In [ ]:
word2vec_model = KeyedVectors.load_word2vec_format(r'D:\ML_Projects\Vehicle_Insurance_Claims_Prediction\models\GoogleNews-vectors-negative300.bin', binary=True)
vocab_size = word2vec_model.vector_size  # Size of Word2Vec embeddings
qa_data = pd.read_csv(r'D:\ML_Projects\AI_Tech_ChatBot\Data\ChatGPT_chatlogs\GPT_chatlogs_all_filtered_Q50_A50_10K.csv')

def get_word_vector(word):
    try:
        return word2vec_model[word]
    except KeyError:
        return np.zeros(word2vec_model.vector_size)

In [12]:
print(get_word_vector(' '))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [30]:
block_size = 50

In [19]:
def pad_or_truncate(sequence, max_length):
    if len(sequence) > max_length:
        return sequence[:max_length]
    elif len(sequence) < max_length:
        padding = [np.zeros(word2vec_model.vector_size)] * (max_length - len(sequence))
        return sequence + padding
    return sequence

In [31]:
def preprocess_data(data):
    questions = []
    answers = []
    for i in range(len(data)):
        try:
            question = data['Question'][i].split()
            answer = data['Answer'][i].split()
        except:
            continue
        question_vectors = [get_word_vector(w) for w in question]
        answer_vectors = [get_word_vector(w) for w in answer]
        print('question: ', question)
        questions.append(pad_or_truncate(question_vectors, block_size))
        print('question padded: ', pad_or_truncate(question_vectors, block_size))
        answers.append(pad_or_truncate(answer_vectors, block_size))
        if i == 0:
            break
    return np.array(questions), np.array(answers)

questions, answers = preprocess_data(qa_data)

question:  ['Would', 'you', 'like', 'to', 'play', 'a', 'game']
question padded:  [array([ 0.16113281,  0.18261719,  0.20703125,  0.5546875 , -0.20410156,
        0.06835938, -0.00585938,  0.04321289, -0.03491211,  0.18359375,
       -0.23828125, -0.32421875, -0.3515625 , -0.1328125 ,  0.12060547,
        0.11523438,  0.12792969,  0.17675781,  0.06738281, -0.00396729,
        0.21582031,  0.15136719,  0.36914062, -0.12792969, -0.05957031,
        0.01721191, -0.27539062,  0.19042969, -0.15332031,  0.28320312,
        0.09814453,  0.05981445, -0.17578125,  0.02941895, -0.140625  ,
        0.296875  ,  0.26953125, -0.00927734, -0.01507568,  0.27539062,
       -0.21875   , -0.27929688,  0.2578125 , -0.19726562,  0.11865234,
        0.11767578,  0.07910156, -0.04638672,  0.16113281, -0.22265625,
       -0.578125  ,  0.10253906,  0.13574219, -0.01135254,  0.28515625,
        0.14746094, -0.01257324,  0.08789062,  0.19238281,  0.06591797,
        0.11230469, -0.17675781, -0.39257812, -0.07177